language: go

go:
  - 1.5.2

before_install:
  - go get gopkg.in/check.v1
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - ./.test-cover.sh
notifications:
  email:
    - eduardo@niclabs.cl